version: '3.9'

services:
  web:
    build: .
    container_name: ch_web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=['localhost', '127.0.0.1']"
      - "DJANGO_SECRET_KEY=django-insecure-k2*+9a)tl0&koj(oq&s4b53^=)euv0^nztb1vzk__!)y(@f(ph"
    ports:
      - '8001:8001'
    depends_on:
      - db

  db:
    image: postgres
    container_name: ch_
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: