version: '3.9'

services:
  web:
    build: .
    container_name: chat_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    #    environment:
    depends_on:
      - db
      - redis


  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
      image: redis
      hostname: redis
      ports:
        - "6379:6379"

volumes:
  postgres_data: