version: '3.9'

services:
  web:
    build: .
    container_name: ch_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=['localhost', '127.0.0.1']"
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres
    container_name: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: