# Generated by Django 4.1 on 2022-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='37kRprJKanAxATz0ADlt', max_length=50, unique=True),
        ),
    ]
