# Generated by Django 4.1 on 2022-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='K9f5Yy3tneZBCBqFBtJN', max_length=50, unique=True),
        ),
    ]
