# Generated by Django 4.1 on 2022-08-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_group_id_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='group_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='PQuqk472FwztrpDTNcve', max_length=50, unique=True),
        ),
    ]
