# Generated by Django 4.1 on 2022-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='5bPMGw731Yn0Ywl7dXE5', max_length=50, unique=True),
        ),
    ]
