# Generated by Django 4.1 on 2022-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='vKmitYbf7VTgNnEQMnwO', max_length=50, unique=True),
        ),
    ]
