# Generated by Django 4.0.6 on 2022-07-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_owner_alter_chat_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='owner',
        ),
    ]
