# Generated by Django 4.1 on 2022-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_content_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='3u6aaItnkBx7oUZfBI8s', max_length=50, unique=True),
        ),
    ]
