# Generated by Django 4.1 on 2022-08-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_body_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='contain_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='recvIsGroup',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='DxhbP5zcp4lk0E71tHcc', max_length=50, unique=True),
        ),
    ]
