# Generated by Django 4.1 on 2022-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_content_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recvIsGroup',
            new_name='Received_from_the_group',
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='9y8fyoLSX4kTU6LB0PzX', max_length=50, unique=True),
        ),
    ]
