# Generated by Django 4.0.6 on 2022-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/static/img/index.png', null=True, upload_to='profile/group/%y/%m/%d/'),
        ),
    ]
