# Generated by Django 4.1 on 2022-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_recvisgroup_message_received_from_the_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contain_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/image/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='LbtUop6wahLoWSrApDGv', max_length=50, unique=True),
        ),
    ]
