# Generated by Django 4.1 on 2022-08-19 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_chat_link_remove_contactlist_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='LuiEyCAyYPCCd7ou82cC', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contact',
            field=models.ManyToManyField(related_name='contact_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
