# Generated by Django 4.0.6 on 2022-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='cuxwawjbnmxbbpvoggra', max_length=50, unique=True),
        ),
    ]
