# Generated by Django 4.1 on 2022-08-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chat_image_alter_chat_link_alter_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='PwsmegR8gWM33YmqfAAI', max_length=50, unique=True),
        ),
    ]
