# Generated by Django 4.1 on 2022-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='cIXgHIZ5QT4sAGF0q4lY', max_length=50, unique=True),
        ),
    ]
