# Generated by Django 4.0.6 on 2022-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='uZ78i9XqoaRBaBv3DLvF', max_length=50, unique=True),
        ),
    ]
