# Generated by Django 4.1 on 2022-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/group_profile.png', null=True, upload_to='profile/group/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='AmiiPiSz2RxK02D8yWTj', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/image/%y/%m/%d/'),
        ),
    ]
