# Generated by Django 4.1 on 2022-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_contact_list'),
        ('chat', '0010_alter_chat_link_contactlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='uuCy0DtxmFsNwNcd97G3', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
