# Generated by Django 4.1 on 2022-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_image_alter_chat_link_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='3yl0d0L2llewkE43N7U2', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/index.png', null=True, upload_to='chat/image/%y/%m/%d/'),
        ),
    ]
