# Generated by Django 4.0.6 on 2022-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/image/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='FUAPPk095SPtTVo1sR1B', max_length=50, unique=True),
        ),
    ]
