# Generated by Django 4.0.6 on 2022-07-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_image_alter_chat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='zU6DyBF5nll9LevGSTer', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
