# Generated by Django 4.0.6 on 2022-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_link_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='contain_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='0UlGmEU3RFX1A3PlOlHP', max_length=50, unique=True),
        ),
    ]
