# Generated by Django 4.0.6 on 2022-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chat_contain_image_alter_chat_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contain_image',
        ),
        migrations.AddField(
            model_name='message',
            name='contain_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='PrYsYif8Hjx0ZGXY2tY2', max_length=50, unique=True),
        ),
    ]
