# Generated by Django 4.0.6 on 2022-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_chat_contain_image_message_contain_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='link',
            field=models.CharField(default='MKWUTd5opAUYIC4fd1lJ', max_length=50, unique=True),
        ),
    ]
