# Generated by Django 4.1 on 2022-08-19 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.ManyToManyField(related_name='contact_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
