# Generated by Django 4.1 on 2022-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/index.png', null=True, upload_to='profile/user/%y/%m/%d/'),
        ),
    ]
