# Generated by Django 4.0.6 on 2022-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/image/index.png', null=True, upload_to='profile/user/%y/%m/%d/'),
        ),
    ]
