# Generated by Django 4.1 on 2022-08-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_contact_profile_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_list',
        ),
    ]
